#### creating array from list,func,iterable,string :
#### np.array(l),np.asarray(l),np.matrix(l) : from list
#### np.fromfunction(take func)
#### np.fromiter(take iterable,data type)
#### np.fromstring( "vi","ash",sep=",")

#### creating array from diff type of range :
#### np.arange(2.3,4.6) ,np.linespace(1,5,10) go from 1 to 5 create 10 div
#### np.logspace(2,5,10,base=2),np.zeros(5),np.zeros((2,5)),np.zeros((3,4,2))
#### np.ones() simolar to np.zeros  : np.eye() create identity matrix

#### np.random.randint(1,100,(5,5))

#### Deep copy and swallow copy

In [1]:
# Numpy stores the data in an array
# An array is a container used to store the data of same data type


In [ ]:
#why numpy
#Computation is fast>> due to array>>>continous memory location
#mathematical computation

In [ ]:
# Matrix >> a matrix is typically represented as a two-dimensional array, and it can be created 
## using various libraries such as NumPy. NumPy is a popular library in Python for numerical 
## computations and provides efficient implementations for working with arrays and matrices.

In [2]:
import numpy as np

In [3]:
l=[1,5,4,6]
l

[1, 5, 4, 6]

In [4]:
arr=np.array(l)
arr

array([1, 5, 4, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.array([2,6,5])

array([2, 6, 5])

In [7]:
a=np.array([[1,2,4],[8,6,8]])
a

array([[1, 2, 4],
       [8, 6, 8]])

In [8]:
type(a)

numpy.ndarray

In [9]:
b=np.matrix(l)    # matrix is subset of array
b

matrix([[1, 5, 4, 6]])

In [10]:
type(b)

numpy.matrix

In [11]:
l1=[5,6,8]

In [12]:
d=np.array(l1)
d

array([5, 6, 8])

In [13]:
e=d     #swallow copy means changes will reflect

In [14]:
e

array([5, 6, 8])

In [15]:
d[0]=456
d

array([456,   6,   8])

In [16]:
e

array([456,   6,   8])

In [17]:
d=np.copy(e)   #deep copy any changes does not affect array
d

array([456,   6,   8])

In [18]:
e

array([456,   6,   8])

In [19]:
e[0]=999

In [20]:
e

array([999,   6,   8])

In [21]:
d

array([456,   6,   8])

In [22]:
#some functions in numpy

In [23]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [24]:
np.fromfunction(lambda i,j:i*j,(4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [25]:
l3=[6,5,8]

In [26]:
np.fromiter(l3,int)

array([6, 5, 8])

In [27]:
iter=(i+i for i in range(5))
iter

<generator object <genexpr> at 0x7f29d42285f0>

In [28]:
np.fromiter(iter,int)

array([0, 2, 4, 6, 8])

In [29]:
np.fromstring('4,5' ,sep=',')

array([4., 5.])

In [30]:
range(4)

range(0, 4)

In [31]:
list(range(4))

[0, 1, 2, 3]

In [32]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(3.5,10)

array([3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [35]:
np.linspace(1,5,10)   #line taken from 1 to 5 and
                      #broken into 10 equal spaces

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
np.zeros(5)  #1d array

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros(  (3,4)  )  #created a 2d array of 3 coss 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((3,4,2))   # created 3 arrays of 4 cross 2 3d zrray as three parameter is passed so dim is 3

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
np.zeros((3,4,2,3)) #created 12 arrays of 2 cross 3
                    #4d arrays

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [40]:
np.zeros((2,3,2,3)) 
#created 6 arrays of 2 cross 3

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
arr1=np.ones((4,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
import pandas as pd

In [44]:
df=pd.DataFrame(arr1)
df

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0

In [48]:
df.to_excel("saved array as df.xlsx")