#### Numpy Statical func

In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,100,(3,4))
arr

array([[86, 40, 55, 14],
       [ 7, 74,  2, 37],
       [69, 97, 76, 94]])

In [3]:
np.sqrt(arr)

array([[9.2736185 , 6.32455532, 7.41619849, 3.74165739],
       [2.64575131, 8.60232527, 1.41421356, 6.08276253],
       [8.30662386, 9.8488578 , 8.71779789, 9.69535971]])

In [4]:
np.exp(arr)

array([[2.23524660e+37, 2.35385267e+17, 7.69478527e+23, 1.20260428e+06],
       [1.09663316e+03, 1.37338298e+32, 7.38905610e+00, 1.17191424e+16],
       [9.25378173e+29, 1.33833472e+42, 1.01480039e+33, 6.66317622e+40]])

In [5]:
np.sin(arr)

array([[-0.92345845,  0.74511316, -0.99975517,  0.99060736],
       [ 0.6569866 , -0.98514626,  0.90929743, -0.64353813],
       [-0.11478481,  0.37960774,  0.56610764, -0.24525199]])

In [6]:
np.mean(arr)

54.25

#### Numpy char func

In [7]:
arr1=np.array(["vis","ash","prash"])
arr1

array(['vis', 'ash', 'prash'], dtype='<U5')

In [8]:
np.char.capitalize(arr1)

array(['Vis', 'Ash', 'Prash'], dtype='<U5')

In [9]:
np.char.upper(arr1)

array(['VIS', 'ASH', 'PRASH'], dtype='<U5')

#### Numpy Searching and Sorting func

In [35]:
arr2=np.array([2,15,12,85,93,4,54])
arr2

array([ 2, 15, 12, 85, 93,  4, 54])

In [36]:
np.sort(arr2)

array([ 2,  4, 12, 15, 54, 85, 93])

In [44]:
np.extract(arr2>54,arr2)

array([85, 93])

In [46]:
np.where(arr2>45)

(array([3, 4, 6]),)

In [48]:
np.roll(arr2,2)   # shift all element by 2 index

array([ 4, 54,  2, 15, 12, 85, 93])

In [49]:
np.roll(arr2,3)   # shift all element by 3 index

array([93,  4, 54,  2, 15, 12, 85])

In [50]:
import numpy.matlib as nm

In [53]:
nm.zeros((4,10))

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [57]:
nm.array([2,3,5,78,45])

array([ 2,  3,  5, 78, 45])