In [1]:
import numpy as np

In [2]:
arr1=np.ones((4,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
arr1 +5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [4]:
arr1*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [5]:
arr1 **2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr2 = np.eye(3,5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [7]:
arr1 @ arr2   # matrix multiplication

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [8]:
arr3 = np.random.randint(1,100,(3,4))
arr3

array([[55, 56, 96,  8],
       [22, 47, 13,  1],
       [35,  4, 94,  7]])

##### Numpy data type

In [9]:
arr3.ndim

2

In [10]:
arr3.size

12

In [11]:
arr3.shape

(3, 4)

In [12]:
arr3.dtype

dtype('int64')

In [13]:
arr3.T

array([[55, 22, 35],
       [56, 47,  4],
       [96, 13, 94],
       [ 8,  1,  7]])

In [14]:
arr3.reshape(6,2)

array([[55, 56],
       [96,  8],
       [22, 47],
       [13,  1],
       [35,  4],
       [94,  7]])

In [15]:
#case when you dont know in reshape what should be the column count

arr3.reshape(4, -1)  # here any negative value can be given ; also for row

array([[55, 56, 96],
       [ 8, 22, 47],
       [13,  1, 35],
       [ 4, 94,  7]])

#### Numpy Broadcasting

In [16]:
row=np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [17]:
arr3+row

array([[56, 58, 99, 12],
       [23, 49, 16,  5],
       [36,  6, 97, 11]])

In [18]:
arr=np.array([[2,4,6]])
arr


array([[2, 4, 6]])

In [19]:
col=arr.T
col

array([[2],
       [4],
       [6]])

In [20]:
arr3+col

array([[ 57,  58,  98,  10],
       [ 26,  51,  17,   5],
       [ 41,  10, 100,  13]])

#### Indexing and Slicing

In [21]:
arr3

array([[55, 56, 96,  8],
       [22, 47, 13,  1],
       [35,  4, 94,  7]])

In [22]:
arr3[1][3]   # 1st box is for row and 2nd one is for col

1

In [23]:
arr3[1:2,0:3]   

array([[22, 47, 13]])

In [24]:
arr3[1:3,1:3]

array([[47, 13],
       [ 4, 94]])

In [25]:
arr3[arr3>50]

array([55, 56, 96, 94])

In [28]:
arr4=np.random.randint(4,20,(6,7))
arr4

array([[ 4, 11,  4,  8, 18, 16,  7],
       [10, 13,  7, 11,  6, 12,  5],
       [ 9, 15, 15, 14, 16,  7, 11],
       [ 8, 14, 12, 17,  9, 16, 18],
       [ 4, 12,  8,  6,  6, 15, 16],
       [11, 10, 11, 17, 19,  4,  5]])

In [29]:
arr4[2:4,1:3]

array([[15, 15],
       [14, 12]])

In [32]:
arr4[4][5]

15

In [35]:
# o/p needed is 2 and 5 col of size 4
arr4[0:5,[1,4]]     # row will give size ,which col is needed >> pass it as a list

array([[11, 18],
       [13,  6],
       [15, 16],
       [14,  9],
       [12,  6]])

In [37]:
arr4[4:6,[2,5,6]]

array([[ 8, 15, 16],
       [11,  4,  5]])